[workspace]
members = [ "crates/*" ]

[profile.release]
incremental = true
debug = true

[patch.'crates-io']
cargo_metadata = { git = "https://github.com/oli-obk/cargo_metadata.git", rev="f73e27b24e" }
salsa = { git = "https://github.com/matklad/salsa", branch = "panic-hooks" }
languageserver-types = {path="../languageserver-types"}
